In [1]:
import pandas as pd

In [8]:
import pandas as pd
info = {
   "Name": ["Rahul","Harshita","Shradha"],
   "CGPA": [9.3,7.5,8.6]
}
df = pd.DataFrame(info) # pd.Dataframe is an important datastructure for making table of content
print(df)

       Name  CGPA
0     Rahul   9.3
1  Harshita   7.5
2   Shradha   8.6

In [23]:
df

       Name  CGPA
0     Rahul   9.3
1  Harshita   7.5
2   Shradha   8.6

In [9]:
s = pd.Series([1,2,3,4,5]) #A Series is a one-dimensional labeled array in Pandas
print(s,type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'>

In [10]:
S = pd.Series([22,23,25,26], index = ["Adam","Sabrina","Ana","Charlie"])# Labeled is a named Index
print(S)

print(S["Adam"])
print(S.index)
'''
 * Series(Prooerties)
 1. Homogenous = same type of data are store only
 2. Vectorized Opertions = provide lable automatically
 3. Mutuble values, immutable size = Can not change the size but can replace the values

'''

Adam       22
Sabrina    23
Ana        25
Charlie    26
dtype: int64
22
Index(['Adam', 'Sabrina', 'Ana', 'Charlie'], dtype='object')

'\n * Series(Prooerties)\n 1. Homogenous = same type of data are store only\n 2. Vectorized Opertions = provide lable automatically\n 3. Mutuble values, immutable size = Can not change the size but can replace the values\n\n'

In [11]:
# csv data
df = pd.read_csv("employee_data1.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [36]:
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [43]:
df.tail()
# df.tail(2)

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [45]:
df.sample()
df.info()
df.shape
df.describe()
df.columns
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 656.0+ bytes

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64

In [12]:
# AQI Data set
df = pd.read_csv("globalAirQuality.csv")
print(df)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [14]:
df.describe()
'''
Pandas Selecting Data
1. Select Columns 
2. Select Rows(Lable & Index based) - loc& iloc
3. Select Rows & Columns
4. Select single scalar value- at & iat
'''

'\nPandas Selecting Data\n1. Select Columns \n2. Select Rows(Lable & Index based) - loc& iloc\n3. Select Rows & Columns\n4. Select single scalar value- at & iat\n'

In [15]:
df["city"]
df[["city","aqi"]]
df.loc[0]
df.loc[0:2] # ending index is inclusive

df.iloc[0]
df.iloc[0:2] # ending index is exclusive

df.iloc[0:3, 1:6]

df.at[0,"city"]
df.iat[0,2]

'New York'

In [ ]:
# Filtering of Data
df [ (df["aqi"]> 100) & (df["temperature"]>30)]
df[ (df["aqi"]> 100) & (df["temperature"]<30)]
df[(df["aqi"]>100) & (df["temperature"]>30)] 

aqi_data = df[(df["aqi"] > 100)&(df["temperature"]>30)] [["city","aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

# Query
df.query("aqi>100")
'''
query() rules
. Expression as a string
. Column Based reference
. Backticks for col_name with space or special chars 
. Operators (&,|,~,>=,>,<=,<, == etc.)
. @ to reference Python vars
. Chanined comparisons 
'''

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [ ]:
# Pandas Data cleaning
'''
 Handle Missing values 
 . isnull() / isna()
 . isnull().sum()
 . dropna()
 . fillna(value)
 . ffill()
 . bfill()
'''
import pandas as pd
df = pd.read_csv("raw_data (1).csv")
df.isnull
df.isnull().sum()
df.dropna()
df.dropna(axis=1)

df.fillna(0)

age_mean = df["age"].mean()
Cleaned_data = df.copy()
age_mean = Cleaned_data["age"].mean()
Cleaned_data["age"] = Cleaned_data["age"].fillna(age_mean)

df.ffill()
df.bfill(

)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [34]:
# Handle Duplicates
df.duplicated()
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [44]:
# Data types
df.dtypes
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df['gender'].str.upper()
df['gender'].str.lower()
df['gender'].str.capitalize()

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [39]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [38]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0